name: getflutter_app
description: A GetFlutter Demo App

version: 1.0.4+5

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  getflutter:
    path: ../
  flutter_svg: ^0.15.0
  easy_web_view: ^1.0.1
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib/assets/icons/buttons.svg
    - lib/assets/icons/primary.svg
    - lib/assets/icons/secondary.svg
    - lib/assets/icons/success.svg
    - lib/assets/icons/warning.svg
    - lib/assets/icons/danger.svg
    - lib/assets/icons/info.svg
    - lib/assets/icons/dark.svg
    - lib/assets/icons/link.svg
    - lib/assets/icons/light.svg
    - lib/assets/icons/fb.svg
    - lib/assets/icons/twitter.svg
    - lib/assets/icons/whatsapp.svg
    - lib/assets/icons/google.svg
    - lib/assets/icons/dribble.svg
    - lib/assets/icons/youtube.svg
    - lib/assets/icons/slack.svg
    - lib/assets/icons/pinterest.svg
    - lib/assets/icons/linkedin.svg
    - lib/assets/images/image.png
    - lib/assets/images/image1.png
    - lib/assets/images/red.png
    - lib/assets/images/purple.png
    - lib/assets/images/pink.png
    - lib/assets/images/orange.png
    - lib/assets/images/image2.png
    - lib/assets/images/img.png
    - lib/assets/images/img1.png
    - lib/assets/images/img2.png
    - lib/assets/images/card.png
    - lib/assets/images/card1.png
    - lib/assets/images/card2.png
    - lib/assets/images/card3.png
    - lib/assets/images/card5.png
    - lib/assets/images/card4.png
    - lib/assets/icons/buttons.svg
    - lib/assets/icons/badges.svg
    - lib/assets/icons/avatars.svg
    - lib/assets/icons/cards.svg
    - lib/assets/icons/carousels.svg
    - lib/assets/icons/images.svg
    - lib/assets/icons/tabs.svg
    - lib/assets/icons/tiles.svg
    - lib/assets/icons/typography.svg
    - lib/assets/icons/accordion.svg
    - lib/assets/icons/appbar.svg
    - lib/assets/icons/alert.svg
    - lib/assets/icons/toast.svg
    - lib/assets/icons/search-bar.svg
    - lib/assets/icons/toggle.svg
    - lib/assets/icons/gflogo.svg
    - lib/assets/images/gflogo.png
    - lib/assets/images/avatar1.png
    - lib/assets/images/avatar2.png
    - lib/assets/images/avatar3.png
    - lib/assets/images/avatar4.png
    - lib/assets/images/avatar5.png
    - lib/assets/images/avatar6.png
    - lib/assets/images/avatar7.png
    - lib/assets/images/avatar8.png
    - lib/assets/images/avatar9.png
    - lib/assets/images/avatar10.png
    - lib/assets/images/avatar11.png
    - lib/assets/images/avatar12.png
